#!/bin/bash
#$ -cwd
# error = Merged with joblog
#$ -o joblog.$JOB_ID
#$ -j y
## Edit the line below as needed:
#$ -l h_rt=24:00:00,h_data=11G
## Modify the parallel environment
## and the number of cores as needed:
#$ -pe shared 1
# Notify when
#$ -m ea

echo "Job $JOB_ID started on:   " `hostname -s`
echo "Job $JOB_ID started on:   " `date `
echo " "

# load the job environment:
. /u/local/Modules/default/init/modules.sh
module load bedtools

for chr in chrX chr2R chr2L chr3R chr3L; do
    #go over every sample file per chr
    cd fastaFiles/${chr}   
    for file in ${chr}_sample*; do
        #bedtools getfasta -fi $file -bed ../../../ReferenceGenomes_DMel/FunctionalCategories/D.mel_UNIQUE_exons.bed -fo exons_UNIQUE_${file}.fa 
        #rm $file.fai

        #bedtools getfasta -fi $file -bed ../../../ReferenceGenomes_DMel/FunctionalCategories/D.mel_UNIQUE_introns.bed -fo introns_UNIQUE_${file}.fa
        #rm $file.fai
        
        #bedtools getfasta -fi $file -bed ../../../ReferenceGenomes_DMel/FunctionalCategories/D.mel_UNIQUE_intergenic_noHet.bed -fo intergenic_UNIQUE_noHet_${file}.fa
        #rm $file.fai

	#bedtools getfasta -fi $file -bed ../../../ReferenceGenomes_DMel/FunctionalCategories/D.mel_UNIQUE_subintergenic.bed -fo subintergenic_UNIQUE_${file}.fa
        #rm $file.fai
	
	#bedtools getfasta -fi $file -bed ../../../ReferenceGenomes_DMel/FunctionalCategories/D.mel_UNIQUE_putativelyNeutral.bed -fo neutral_UNIQUE_${file}.fa
        #rm $file.fai
    done
    cd ../..
done

# echo job info on joblog:
echo "Job $JOB_ID ended on:   " `hostname -s`
echo "Job $JOB_ID ended on:   " `date `
echo " "

